trigger:
- master
- dev

stages:
- stage: DotnetBuild
  displayName: 'Dotnet Build'
  jobs:
    - job:
      steps:
        - task: DotNetCoreCLI@2
          inputs:
            command: 'build'
            projects: '**/Zedouto.Api.Login/*.csproj'

- stage:
  displayName: 'Publish artifact (AppSettings)'
  dependsOn: 'DotnetBuild'
  condition: in(variables['Build.SourceBranch'], 'refs/heads/master', 'refs/heads/dev')
  jobs:
  - job:
    displayName: 'Publish appsettings'
    steps:
    - script: |
        ls
        ls src/
        ls src/Zedouto.Api.Login/
    
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'src/'
        ArtifactName: 'AppSettings'
        publishLocation: 'Container'