trigger:
- master
- dev

stages:
- stage: DotnetBuild
  displayName: 'Dotnet Build'
  jobs:
    - job:
      steps:
        - task: DotNetCoreCLI@2
          inputs:
            command: 'build'
            projects: '**/Zedouto.Api.Login/*.csproj'

- stage:
  displayName: 'Docker build and Push'
  dependsOn: 'DotnetBuild'
  condition: in(variables['Build.SourceBranch'], 'refs/heads/master', 'refs/heads/dev')
  jobs:
  - job:
    displayName: 'Build and Push Docker an image'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHub - souzamateus99'
        repository: 'souzamateus99/login-api'
        command: 'buildAndPush'
        Dockerfile: 'Dockerfile'

- stage:
  displayName: 'Publish artifact (AppSettings)'
  dependsOn: 'DotnetBuild'
  condition: in(variables['Build.SourceBranch'], 'refs/heads/master', 'refs/heads/dev')
  jobs:
  - job:
    displayName: 'Publish appsettings'
    steps:
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/src/Zedouto.Api.Login/appsettings.json'
        ArtifactName: 'AppSettings'
        publishLocation: 'Container'